version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ghostmarket_db
    restart: always
    ports:
      - "3307:3306" # 
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: ghostmarket
      MYSQL_USER: ghostadmin
      MYSQL_PASSWORD: localpassword123
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: